import type { SealConfig } from '@/types/seal'

export const DEFAULT_SEAL_CONFIG: SealConfig = {
  companyName: '一人独立开发科技有限公司',
  sealName: '人事专用章',
  centerText: '★',
  securityCode: '1234567890123',
  companyFontFamily: 'SimSun',
  sealNameFontFamily: 'SimSun',
  centerFontFamily: 'SimSun',
  securityFontFamily: 'KaiTi',
  companyFontSize: 20,
  companyLetterSpacing: 0,
  companyStretchY: 1,
  companyOffsetY: 4,
  companyBold: false,
  sealNameFontSize: 16,
  sealNameLetterSpacing: 0,
  sealNameStretchY: 1,
  sealNameOffsetX: 0,
  sealNameOffsetY: 0,
  sealNameBold: false,
  centerFontSize: 50,
  centerLetterSpacing: 0,
  centerStretchY: 1,
  centerBold: false,
  securityFontSize: 10,
  securityLetterSpacing: 2,
  securityOffsetY: 4,
  securityStretchY: 1,
  securityBold: false,
  securityFlipX: false,
  securityFlipY: false,
  outerBorderWidth: 6,
  innerBorderWidth: 2,
  innerBorderOffset: 30,
  color: '#ef3f3a',
  diameter: 240,
  roughnessEnabled: false,
  roughnessLevel: 100,
  roughnessDensity: 200,
  roughnessNoise: 10,
}

export const STORAGE_KEYS = {
  currentConfig: 'seal.currentConfig',
  presetList: 'seal.presetList',
} as const
